# Задача 1
### Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет
### array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [53]:
import numpy as np


x = int(input('Введите число "x" больше "0": '))

a = np.arange(x)
a = a[::-1]
a

Введите число "x" больше "0": 15


array([14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

# Задача 2
### Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [8]:
# Я полностью переделал эту задачу, так как вспомнил, что такое вообще диаг.матрица.
#Надеюсь, все правильно.
import numpy as np


x = int(input('Введите число "x" больше "0": '))

c = np.arange(x)
c = c[::-1]
print(np.diag(c))

Введите число "x" больше "0": 9
[[8 0 0 0 0 0 0 0 0]
 [0 7 0 0 0 0 0 0 0]
 [0 0 6 0 0 0 0 0 0]
 [0 0 0 5 0 0 0 0 0]
 [0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0]]


In [11]:
diag_ = np.diag(c)
result = diag_.sum()
print(result)

36


# Задача 3
## Решите систему уравнений:
### 4x + 2y + z = 4
### x + 3y = 12
### 5y + 4z = -3

In [24]:
import numpy as np

matrix_ = np.array([[4,2,1], [1,3,0], [0,5,4]])
vector_ = np.array([4,12,-3])
result = np.linalg.solve(matrix_, vector_)

print(result)

[ 0.46666667  3.84444444 -5.55555556]


# Задача 4


In [66]:
# я сделал новый вариант решения задачи.Предыдущий вариант(ниже) я исправил.

import numpy as np

users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)


next_user_stats = np.array([0, 1, 2, 0, 0, 0])


comparison = [np.dot(stat, next_user_stats) / (np.linalg.norm(stat) * np.linalg.norm(next_user_stats))
    for stat in users_stats]
    
print(f'User ID:{comparison.index(max(comparison))+1}\nCosin:{(max(comparison))}')
    


User ID:8
Cosin:0.9486832980505138


In [65]:
import numpy as np

users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)


next_user_stats = np.array([0, 1, 2, 0, 0, 0])


def cosine(users_stats, next_user_stats):
    len_users_stats = np.linalg.norm(users_stats, axis=1)
    len_next_user_stats = np.linalg.norm(next_user_stats)
    comparison = np.dot(users_stats, next_user_stats) / (len_users_stats * len_next_user_stats)
    return comparison
print(f'User ID:{comparison.index(max(comparison))+1}\nCosin:{(max(comparison))}')

User ID:8
Cosin:0.9486832980505138
